#-------------------------------
# General Site Settings

menu:
- {name: 'About',    url: 'about'}
- {name: 'Data Science', url: 'ds'}
- {name: 'GIS', url: 'gis'}
- {name: 'UI/UX', url: 'ui-ux'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# GIS Section

gis:
- {name: 'GIS Classwork',   url: 'gis-classwork'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/andrewxie43'}
- {icon: 'dribbble',  link: 'https://dribbble.com/ayxie2'}
- {icon: 'behance',  link: 'https://www.behance.net/andrewxie1'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/andrew-x-890762165/'}
- {icon: 'envelope',  link: 'mailto:ayxie2@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
